### ISSUE TITLE
How to add new style images?

### ISSUE THREAD

**Issue by ruanjiyang** [Azmarie/Caricature-Your-Face#2]
Dear Azmarie,

I want to add new style images. so I want to know how to create *.ljson files for new style face images?  thanks!

**Comment by Azmarie** [comment]
The current style images are from [The Face of Art](https://faculty.idc.ac.il/arik/site/foa/face-of-art.asp) that's why they are in `ljson` format.

If you want to introduce new style images, you could simply use standard library such as `dlib` to detect the points and save as `txt` files (such as using the `face_landmark_detection.py` script), no need to create `ljson` files. 

Hope this helps.

**Comment by ruanjiyang** [comment]
> The current style images are from [The Face of Art](https://faculty.idc.ac.il/arik/site/foa/face-of-art.asp) that's why they are in `ljson` format.
> 
> If you want to introduce new style images, you could simply use standard library such as `dlib` to detect the points and save as `txt` files (such as using the `face_landmark_detection.py` script), no need to create `ljson` files.
> 
> Hope this helps.

Thanks! Azmarie.  got it.
